import { db, tripsTable } from "@workspace/db";

const trips = [
  {
    title: "جولة تركيا الرائعة",
    description: "اكتشف روعة تركيا بين التاريخ العريق والطبيعة الخلابة في إسطنبول وكابادوكيا",
    destination: "إسطنبول",
    country: "تركيا",
    imageUrl: "https://picsum.photos/seed/istanbul/800/600",
    price: 2800,
    duration: 7,
    maxCapacity: 25,
    availableSpots: 18,
    startDate: "2026-05-01",
    endDate: "2026-05-08",
    featured: true,
    rating: 4.9,
    reviewCount: 89,
    includes: ["تذاكر طيران", "إقامة فندقية", "رحلة البالون في كابادوكيا", "جولة البوسفور", "وجبات منتقاة"],
  },
  {
    title: "المالديف جنة الأرض",
    description: "عطلة استثنائية في الشعاب المرجانية والشواطئ البيضاء الساحرة في جزر المالديف",
    destination: "ماليه",
    country: "المالديف",
    imageUrl: "https://picsum.photos/seed/maldives/800/600",
    price: 8500,
    duration: 6,
    maxCapacity: 10,
    availableSpots: 6,
    startDate: "2026-06-10",
    endDate: "2026-06-16",
    featured: true,
    rating: 5.0,
    reviewCount: 56,
    includes: ["تذاكر طيران", "فيلا على الماء", "غوص وسنوركلينج", "وجبات كاملة", "سبا"],
  },
  {
    title: "باريس رومانسية",
    description: "اكتشف سحر باريس مدينة الأنوار والرومانسية مع زيارة برج إيفل والمتاحف الشهيرة",
    destination: "باريس",
    country: "فرنسا",
    imageUrl: "https://picsum.photos/seed/paris/800/600",
    price: 4200,
    duration: 5,
    maxCapacity: 15,
    availableSpots: 10,
    startDate: "2026-07-20",
    endDate: "2026-07-25",
    featured: false,
    rating: 4.7,
    reviewCount: 203,
    includes: ["تذاكر طيران", "فندق وسط المدينة", "جولة سيتي تور", "رحلة في نهر السين", "مرشد سياحي عربي"],
  },
  {
    title: "اليابان أرض الساموراي",
    description: "رحلة ثقافية استثنائية إلى اليابان لاستكشاف طوكيو وكيوتو وأوساكا",
    destination: "طوكيو",
    country: "اليابان",
    imageUrl: "https://picsum.photos/seed/tokyo/800/600",
    price: 6500,
    duration: 10,
    maxCapacity: 20,
    availableSpots: 12,
    startDate: "2026-08-05",
    endDate: "2026-08-15",
    featured: true,
    rating: 4.9,
    reviewCount: 78,
    includes: ["تذاكر طيران", "فندق 4 نجوم", "تجربة اللباس التقليدي", "جولة فوجي", "تذاكر المعالم السياحية"],
  },
  {
    title: "مصر أم الدنيا",
    description: "رحلة تاريخية إلى أرض الفراعنة لزيارة الأهرامات وأبو الهول والمتحف المصري",
    destination: "القاهرة",
    country: "مصر",
    imageUrl: "https://picsum.photos/seed/egypt/800/600",
    price: 1800,
    duration: 4,
    maxCapacity: 30,
    availableSpots: 22,
    startDate: "2026-04-25",
    endDate: "2026-04-29",
    featured: false,
    rating: 4.6,
    reviewCount: 167,
    includes: ["تذاكر طيران", "فندق فئة A", "زيارة الأهرامات", "رحلة نيلية", "مرشد سياحي"],
  },
  {
    title: "إيطاليا في أسبوع",
    description: "استكشف جمال روما وفينيسيا وفلورنسا في رحلة أوروبية لا تنسى",
    destination: "روما",
    country: "إيطاليا",
    imageUrl: "https://picsum.photos/seed/rome/800/600",
    price: 5200,
    duration: 8,
    maxCapacity: 18,
    availableSpots: 9,
    startDate: "2026-09-01",
    endDate: "2026-09-09",
    featured: false,
    rating: 4.8,
    reviewCount: 145,
    includes: ["تذاكر طيران", "فنادق مختارة", "قطار بين المدن", "جولات إرشادية", "وجبات مختارة"],
  },
  {
    title: "المغرب أرض الألوان",
    description: "رحلة ساحرة إلى المغرب بين مراكش الحمراء وصحراء الساحل والجبال الخضراء",
    destination: "مراكش",
    country: "المغرب",
    imageUrl: "https://picsum.photos/seed/morocco/800/600",
    price: 2200,
    duration: 6,
    maxCapacity: 20,
    availableSpots: 14,
    startDate: "2026-05-15",
    endDate: "2026-05-21",
    featured: false,
    rating: 4.7,
    reviewCount: 92,
    includes: ["تذاكر طيران", "رياض تقليدي", "جولة الصحراء", "حمام مغربي", "وجبات تقليدية"],
  },
];

async function seed() {
  for (const trip of trips) {
    await db.insert(tripsTable).values(trip).onConflictDoNothing();
    console.log(`Seeded: ${trip.title}`);
  }
  console.log("Done!");
  process.exit(0);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
