uploads = []
generated = []

[[outputs]]
id = "pPPFMW1HEzHXL3L9ve-pK"
uri = "file://travel-agency-project.tar.gz"
type = "unspecified"
title = "مشروع وكالة شويعر للسياحة والأسفار - النسخة الكاملة"

[[outputs]]
id = "SPfUZGYcxdhB3iH_SSQ1P"
uri = "file://travel-agency-final.tar.gz"
type = "unspecified"
title = "مشروع وكالة شويعر للسياحة والأسفار - النسخة النهائية"

[[outputs]]
id = "uaBmxqPy7GXK_yzelKBgV"
uri = "file://project-documentation.md"
type = "text"
title = "الملف الكامل — وكالة شويعر للسياحة والأسفار"

[[outputs]]
id = "W3qAi4Vdw-Nwu7D_T6eJ5"
uri = "file://chouiaar-travel-agency.zip"
type = "unspecified"
title = "وكالة شويعر للسياحة والأسفار — المشروع الكامل (ZIP)"
